### ISSUE TITLE
unable to run the examples

### ISSUE THREAD

**Issue by dcrisan** [WZBSocialScienceCenter/geovoronoi#4]
I am running python3.7 with everything installed and when running the examples I get the following error:

Traceback (most recent call last):
  File "duplicate_points.py", line 111, in <module>
    points_markersize=np.array(count_per_pt)*10)
  File "/Users/dianacrisan/Library/Python/3.7/lib/python/site-packages/geovoronoi/plotting.py", line 137, in plot_voronoi_polys_with_points_in_area
    _plot_polygon_collection_with_color(ax, [area_shape], color=area_color, edgecolor=area_edgecolor, **plot_area_opts)
  File "/Users/dianacrisan/Library/Python/3.7/lib/python/site-packages/geovoronoi/plotting.py", line 204, in _plot_polygon_collection_with_color
    geoms, _ = _flatten_multi_geoms(geoms)
  File "/Users/dianacrisan/Library/Python/3.7/lib/python/site-packages/geopandas/plotting.py", line 30, in _flatten_multi_geoms
    if not geoms.geom_type.str.startswith('Multi').any():
AttributeError: 'list' object has no attribute 'geom_type'

**Comment by internaut** [comment]
Thanks for reporting this. It was a compatibility issue related to the latest release of GeoPandas. Update to the new geovoronoi version 0.1.1 and it should work.
